< infile cat | ls > outfile
< infile cat | ls > outfile
< infile cat | ls > outfile
< infile cat | ls > outfile
< infile cat | ls > outfile
< infile cat | ls > outfile
< infile cat | ls > outfile
< infile cat | ls > outfile
< infile cat | ls > outfile
< infile cat | ls > outfile
< infile cat | ls > outfile
< infile cat | ls > outfile
< infile cat | ls > outfile
< infile cat | ls > outfile
< infile cat | ls > outfile
< infile cat | ls > outfile
< infile cat | ls > outfile
< infile cat | ls > outfile
< infile cat | ls > outfile
< infile cat | ls > outfile
< infile cat | ls > outfile
< infilelkj cat | ls > outfile
< infilelkj cat | ls > outfile
< infilelkj cat | ls > outfile
< infilelkj cat | ls > outfile
< infilelkj cat | ls > outfile
< infile cat | ls > outfile
< infile cat | ls > outfile
< infile cat | ls > outfile
< infile cat | ls > outfile
< infile cat | ls > outfile
< infile cat | ls > outfile
< infile cat | ls > outfile
